name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "VITE_IS_API_KEY=${{ secrets.VITE_IS_API_KEY }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest
          build-args: |
            VITE_IS_API_KEY=${{ secrets.VITE_IS_API_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest
            docker stop app-container || true
            docker rm app-container || true
            docker run -d --name app-container -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest
