name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 환경 변수 파일 생성
      - name: Create env file
        run: |
          echo "VITE_IS_API_KEY=${{ secrets.VITE_IS_API_KEY }}" > .env

      # 의존성 설치 및 빌드
      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest
          build-args: |
            VITE_IS_API_KEY=${{ secrets.VITE_IS_API_KEY }}

      # EC2에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # EC2에서 Docker 이미지 풀
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest
            # 기존 컨테이너 중지 및 삭제
            docker stop app-container || true
            docker rm app-container || true
            # 새 컨테이너 실행
            docker run -d --name app-container -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest
